#!/usr/bin/env python3
"""
Drift Detection Reporting App - Streamlit Version
Displays drift detection reports and status from Module 3 MLOps pipeline
"""

import streamlit as st
import json
import os
from pathlib import Path


# Get the project root directory
try:
    BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
except NameError:
    # In Jupyter notebooks, __file__ is not defined
    BASE_DIR = os.getcwd()

# Set up paths
MODULE3_PATH = os.path.join(BASE_DIR, "module3")
OUTPUTS_PATH = os.path.join(BASE_DIR, "outputs")

# Configure page
st.set_page_config(
    page_title="Drift Detection Report",
    page_icon="📊",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Custom CSS for better styling
st.markdown("""
<style>
    .main > div {
        padding-top: 2rem;
    }
    .status-good {
        color: #28a745;
        font-weight: bold;
    }
    .status-warning {
        color: #ff9800;
        font-weight: bold;
    }
    .status-alert {
        color: #dc3545;
        font-weight: bold;
    }
</style>
""", unsafe_allow_html=True)


def load_drift_report():
    """Load the drift report HTML file"""
    report_path = os.path.join(MODULE3_PATH, "1_drift_report_explicit.html")

    if os.path.exists(report_path):
        with open(report_path, 'r') as f:
            return f.read()
    else:
        return None


def load_drift_status():
    """Load the drift status from JSON file"""
    status_path = os.path.join(OUTPUTS_PATH, "drift_status.json")

    if os.path.exists(status_path):
        try:
            with open(status_path, 'r') as f:
                return json.load(f)
        except json.JSONDecodeError:
            return None
    else:
        return None


def get_status_color(status):
    """Return appropriate color and emoji for status"""
    status_lower = status.lower() if status else ""

    if status_lower == "detected":
        return "🔴", "status-alert"
    elif status_lower == "warning":
        return "🟡", "status-warning"
    elif status_lower == "stable":
        return "🟢", "status-good"
    else:
        return "⚪", ""


def main():
    """Main Streamlit application"""

    st.title("📊 Drift Detection Report")
    st.markdown("**Module 3: Proactive MLOps - Data Drift Detection & Retraining**")

    # Sidebar
    with st.sidebar:
        st.header("📋 About")
        st.markdown("""
        This dashboard displays the latest drift detection report
        generated by the MLOps pipeline.

        **Data Sources:**
        - Report: `module3/1_drift_report_explicit.html`
        - Status: `outputs/drift_status.json`
        """)

        st.divider()

        st.header("🔄 How to Generate Report")
        st.markdown("""
        To generate a new drift report, run:
        ```
        python module3/1_check_drift.py
        ```
        """)

    # Load data
    drift_status = load_drift_status()
    drift_report_html = load_drift_report()

    # Display status section
    if drift_status:
        st.header("📈 Drift Status")

        status = drift_status.get("status", "UNKNOWN")
        message = drift_status.get("message", "No message available")

        emoji, css_class = get_status_color(status)

        col1, col2 = st.columns([1, 4])
        with col1:
            st.markdown(f"### {emoji}")
        with col2:
            st.markdown(f"### {status}")

        st.markdown(f"**Message:** {message}")

        # Display additional details if available
        if "timestamp" in drift_status:
            st.caption(f"Last checked: {drift_status['timestamp']}")

        st.divider()
    else:
        st.warning(
            "⚠️ Drift status file not found. "
            "Please run `python module3/1_check_drift.py` first."
        )

    # Display drift report
    st.header("📋 Detailed Drift Report")

    if drift_report_html:
        st.components.v1.html(drift_report_html, height=800, scrolling=True)
    else:
        st.error(
            "❌ Drift report not found. "
            "Please run `python module3/1_check_drift.py` first."
        )
        st.info(
            "Expected location: `module3/1_drift_report_explicit.html`"
        )

    st.divider()

    # Debug information (only in development)
    with st.expander("🔧 Debug Information"):
        st.markdown("**File Paths:**")
        st.code(f"BASE_DIR: {BASE_DIR}")
        st.code(f"MODULE3_PATH: {MODULE3_PATH}")
        st.code(f"OUTPUTS_PATH: {OUTPUTS_PATH}")

        st.markdown("**File Existence:**")
        report_exists = os.path.exists(os.path.join(MODULE3_PATH, "1_drift_report_explicit.html"))
        status_exists = os.path.exists(os.path.join(OUTPUTS_PATH, "drift_status.json"))

        st.write(f"📄 Drift Report exists: {report_exists}")
        st.write(f"📄 Drift Status exists: {status_exists}")


if __name__ == "__main__":
    main()
