name: ML Ops Hands on Lab 
description: "Prototype to demonstrate machine learning operations in production"
author: "Cloudera"
date: "2025-02-13"
specification_version: 1.0
prototype_version: 1.0
environment_variables:

  CONNECTION_NAME:
    default: "go01-demo-aws"
    description: "datalake connection name"
runtimes: 
  - editor: Workbench
    kernel: Python 3.10
    edition: Standard
    version: "2024.10"
    addons: [Spark 3.3.0 - CDE 1.22.0]
    
tasks:
  - type: run_session
    name: Install Dependencies
    script: shared_utils/install-dependencies.py
    short_summary: Install Dependencies
    kernel: python3
    cpu: 8
    memory: 16

